version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-memory-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
      - "18001:8001"
    volumes:
      - redis_data:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      redis-stack-server
      --save 60 1
      --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redis_memory_net

  api:
    build:
      context: https://github.com/redis-developer/agent-memory-server.git
      dockerfile: Dockerfile
    container_name: redis-memory-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LONG_TERM_MEMORY=True
      - WINDOW_SIZE=20
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
      - DISABLE_AUTH=true  # Internal LAN only
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redis_memory_net

  mcp:
    build:
      context: https://github.com/redis-developer/agent-memory-server.git
      dockerfile: Dockerfile
    container_name: redis-memory-mcp
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=9000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LONG_TERM_MEMORY=True
      - WINDOW_SIZE=20
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
      - DISABLE_AUTH=true
    depends_on:
      redis:
        condition: service_healthy
    command: ["uv", "run", "agent-memory", "mcp", "--mode", "sse"]
    networks:
      - redis_memory_net

  mcp-stdio:
    build:
      context: https://github.com/redis-developer/agent-memory-server.git
      dockerfile: Dockerfile
    container_name: redis-memory-mcp-stdio
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LONG_TERM_MEMORY=True
      - WINDOW_SIZE=20
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
      - DISABLE_AUTH=true
    depends_on:
      redis:
        condition: service_healthy
    command: ["uv", "run", "agent-memory", "mcp", "--mode", "stdio"]
    networks:
      - redis_memory_net

  task-worker:
    build:
      context: https://github.com/redis-developer/agent-memory-server.git
      dockerfile: Dockerfile
    container_name: redis-memory-task-worker
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
    depends_on:
      redis:
        condition: service_healthy
    command: ["uv", "run", "agent-memory", "task-worker", "--concurrency", "2"]
    networks:
      - redis_memory_net

  # Optional monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: redis-memory-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - redis_memory_net

networks:
  redis_memory_net:
    driver: bridge

volumes:
  redis_data:
  prometheus_data: