# /deployment/configs/alerts.yml
groups:
  - name: redis_memory_central_alerts
    rules:
      - alert: RedisMemoryApiDown
        expr: up{job="redis-memory-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis Memory API is down (job {{ $labels.job }})"
          description: "The FastAPI application is not responding to scrapes."

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down (job {{ $labels.job }})"
          description: "The Redis instance is not responding."

      - alert: HighMemoryUsageRedis
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in Redis (job {{ $labels.job }})"
          description: "Redis is using over 80% of its allocated maxmemory."

      - alert: RedisDisconnectedFromApi
        expr: redis_connected == 0
        for: 2m
        labels:
            severity: critical
        annotations:
            summary: "API cannot connect to Redis"
            description: "The API health endpoint reports that Redis is not connected."