global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Add this section
rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [] # Configure Alertmanager here in the future

scrape_configs:
  - job_name: 'redis-memory-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] # Using an exporter is best practice

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']